module.exports.INIT_NOTEBOOK_EVENT = 'init'
module.exports.FIND_SUB_FILES = 'find-sub-files'
module.exports.FIND_FILE = 'find-file'
module.exports.MODIFY_FILE_NAME = 'modify-file-name'
module.exports.MODIFY_FILE_CONTENT = 'modify-file-content'
module.exports.CREATE_FILE_OR_DIR = 'create-file-or-dir'
