module.exports.INIT_NOTEBOOK_EVENT = 'init'
module.exports.FIND_SUB_FILES = 'find-sub-files'
module.exports.FIND_FILE = 'find-file'
module.exports.MODIFY_FILE_NAME = 'modify-file-name'
module.exports.MODIFY_FILE_CONTENT = 'modify-file-content'
module.exports.CREATE_FILE_OR_DIR = 'create-file-or-dir'
module.exports.DELETE_FILE_OR_DIR = 'delete_file_or_dir'
module.exports.GET_NOTES_TAGS = 'get_notes_tags'
module.exports.GET_CARDS_REVIEW = 'get_cards_review'
module.exports.OPEN_DIR = 'open_dir'
module.exports.PUSH_TO_REPO = 'push_to_repo'
module.exports.PUSH_TO_REPO_FINISHED = 'push_to_repo_finished'

module.exports.CREATE_TIMECARD_PLAN = 'create_timecard_plan'
module.exports.GET_TIMECARDS_BY_YEAR = 'get_timecards_by_year'
