module.exports = {
  SWITCH_LEFT_MENU_VISIBLE_CMD: 'CmdOrCtrl+1',
  SWITCH_SUB_MENU_VISIBLE_CMD: 'CmdOrCtrl+2',
  SWITCH_SEARCH_BAR_VISIBLE_CMD: 'CmdOrCtrl+f',
  SWITCH_RECENTLY_MODAL_VISIBLE_CMD: 'CmdOrCtrl+e',
}